version: 2

project_name: xpb

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/xpb
    binary: xpb
    ldflags:
      - -X github.com/PocketBuilds/xpb.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
